/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DemoAzulRouteImport } from './routes/demo-azul'
import { Route as ApresentacaoRouteImport } from './routes/apresentacao'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as PublicIndexRouteImport } from './routes/_public.index'
import { Route as AdminRelatoriosRouteImport } from './routes/admin.relatorios'
import { Route as AdminConfiguracoesRouteImport } from './routes/admin.configuracoes'
import { Route as AdminAtividadeRouteImport } from './routes/admin.atividade'
import { Route as PublicVendaSeuVeiculoRouteImport } from './routes/_public.venda-seu-veiculo'
import { Route as PublicSobreRouteImport } from './routes/_public.sobre'
import { Route as PublicPoliticaDePrivacidadeRouteImport } from './routes/_public.politica-de-privacidade'
import { Route as PublicFinanciamentoRouteImport } from './routes/_public.financiamento'
import { Route as PublicEstoqueRouteImport } from './routes/_public.estoque'
import { Route as PublicContatoRouteImport } from './routes/_public.contato'
import { Route as AdminVendasIndexRouteImport } from './routes/admin.vendas.index'
import { Route as AdminVeiculosIndexRouteImport } from './routes/admin.veiculos.index'
import { Route as AdminFinanceiroIndexRouteImport } from './routes/admin.financeiro.index'
import { Route as AdminVendasNovaRouteImport } from './routes/admin.vendas.nova'
import { Route as AdminVendasComissoesRouteImport } from './routes/admin.vendas.comissoes'
import { Route as AdminVeiculosQualidadeRouteImport } from './routes/admin.veiculos.qualidade'
import { Route as AdminVeiculosProducaoRouteImport } from './routes/admin.veiculos.producao'
import { Route as AdminVeiculosNovoRouteImport } from './routes/admin.veiculos.novo'
import { Route as AdminVeiculosIdRouteImport } from './routes/admin.veiculos.$id'
import { Route as AdminMarketingPublicacoesRouteImport } from './routes/admin.marketing.publicacoes'
import { Route as AdminMarketingConteudoRouteImport } from './routes/admin.marketing.conteudo'
import { Route as AdminFinanceiroReceberRouteImport } from './routes/admin.financeiro.receber'
import { Route as AdminFinanceiroPagarRouteImport } from './routes/admin.financeiro.pagar'
import { Route as AdminFinanceiroCustosRouteImport } from './routes/admin.financeiro.custos'
import { Route as PublicVeiculoSlugRouteImport } from './routes/_public.veiculo.$slug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoAzulRoute = DemoAzulRouteImport.update({
  id: '/demo-azul',
  path: '/demo-azul',
  getParentRoute: () => rootRouteImport,
} as any)
const ApresentacaoRoute = ApresentacaoRouteImport.update({
  id: '/apresentacao',
  path: '/apresentacao',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const AdminRelatoriosRoute = AdminRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfiguracoesRoute = AdminConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAtividadeRoute = AdminAtividadeRouteImport.update({
  id: '/atividade',
  path: '/atividade',
  getParentRoute: () => AdminRoute,
} as any)
const PublicVendaSeuVeiculoRoute = PublicVendaSeuVeiculoRouteImport.update({
  id: '/venda-seu-veiculo',
  path: '/venda-seu-veiculo',
  getParentRoute: () => PublicRoute,
} as any)
const PublicSobreRoute = PublicSobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => PublicRoute,
} as any)
const PublicPoliticaDePrivacidadeRoute =
  PublicPoliticaDePrivacidadeRouteImport.update({
    id: '/politica-de-privacidade',
    path: '/politica-de-privacidade',
    getParentRoute: () => PublicRoute,
  } as any)
const PublicFinanciamentoRoute = PublicFinanciamentoRouteImport.update({
  id: '/financiamento',
  path: '/financiamento',
  getParentRoute: () => PublicRoute,
} as any)
const PublicEstoqueRoute = PublicEstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => PublicRoute,
} as any)
const PublicContatoRoute = PublicContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => PublicRoute,
} as any)
const AdminVendasIndexRoute = AdminVendasIndexRouteImport.update({
  id: '/vendas/',
  path: '/vendas/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVeiculosIndexRoute = AdminVeiculosIndexRouteImport.update({
  id: '/veiculos/',
  path: '/veiculos/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinanceiroIndexRoute = AdminFinanceiroIndexRouteImport.update({
  id: '/financeiro/',
  path: '/financeiro/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVendasNovaRoute = AdminVendasNovaRouteImport.update({
  id: '/vendas/nova',
  path: '/vendas/nova',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVendasComissoesRoute = AdminVendasComissoesRouteImport.update({
  id: '/vendas/comissoes',
  path: '/vendas/comissoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVeiculosQualidadeRoute = AdminVeiculosQualidadeRouteImport.update({
  id: '/veiculos/qualidade',
  path: '/veiculos/qualidade',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVeiculosProducaoRoute = AdminVeiculosProducaoRouteImport.update({
  id: '/veiculos/producao',
  path: '/veiculos/producao',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVeiculosNovoRoute = AdminVeiculosNovoRouteImport.update({
  id: '/veiculos/novo',
  path: '/veiculos/novo',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVeiculosIdRoute = AdminVeiculosIdRouteImport.update({
  id: '/veiculos/$id',
  path: '/veiculos/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMarketingPublicacoesRoute =
  AdminMarketingPublicacoesRouteImport.update({
    id: '/marketing/publicacoes',
    path: '/marketing/publicacoes',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminMarketingConteudoRoute = AdminMarketingConteudoRouteImport.update({
  id: '/marketing/conteudo',
  path: '/marketing/conteudo',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinanceiroReceberRoute = AdminFinanceiroReceberRouteImport.update({
  id: '/financeiro/receber',
  path: '/financeiro/receber',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinanceiroPagarRoute = AdminFinanceiroPagarRouteImport.update({
  id: '/financeiro/pagar',
  path: '/financeiro/pagar',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinanceiroCustosRoute = AdminFinanceiroCustosRouteImport.update({
  id: '/financeiro/custos',
  path: '/financeiro/custos',
  getParentRoute: () => AdminRoute,
} as any)
const PublicVeiculoSlugRoute = PublicVeiculoSlugRouteImport.update({
  id: '/veiculo/$slug',
  path: '/veiculo/$slug',
  getParentRoute: () => PublicRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/apresentacao': typeof ApresentacaoRoute
  '/demo-azul': typeof DemoAzulRoute
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/contato': typeof PublicContatoRoute
  '/estoque': typeof PublicEstoqueRoute
  '/financiamento': typeof PublicFinanciamentoRoute
  '/politica-de-privacidade': typeof PublicPoliticaDePrivacidadeRoute
  '/sobre': typeof PublicSobreRoute
  '/venda-seu-veiculo': typeof PublicVendaSeuVeiculoRoute
  '/admin/atividade': typeof AdminAtividadeRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/relatorios': typeof AdminRelatoriosRoute
  '/admin/': typeof AdminIndexRoute
  '/veiculo/$slug': typeof PublicVeiculoSlugRoute
  '/admin/financeiro/custos': typeof AdminFinanceiroCustosRoute
  '/admin/financeiro/pagar': typeof AdminFinanceiroPagarRoute
  '/admin/financeiro/receber': typeof AdminFinanceiroReceberRoute
  '/admin/marketing/conteudo': typeof AdminMarketingConteudoRoute
  '/admin/marketing/publicacoes': typeof AdminMarketingPublicacoesRoute
  '/admin/veiculos/$id': typeof AdminVeiculosIdRoute
  '/admin/veiculos/novo': typeof AdminVeiculosNovoRoute
  '/admin/veiculos/producao': typeof AdminVeiculosProducaoRoute
  '/admin/veiculos/qualidade': typeof AdminVeiculosQualidadeRoute
  '/admin/vendas/comissoes': typeof AdminVendasComissoesRoute
  '/admin/vendas/nova': typeof AdminVendasNovaRoute
  '/admin/financeiro/': typeof AdminFinanceiroIndexRoute
  '/admin/veiculos/': typeof AdminVeiculosIndexRoute
  '/admin/vendas/': typeof AdminVendasIndexRoute
}
export interface FileRoutesByTo {
  '/apresentacao': typeof ApresentacaoRoute
  '/demo-azul': typeof DemoAzulRoute
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/contato': typeof PublicContatoRoute
  '/estoque': typeof PublicEstoqueRoute
  '/financiamento': typeof PublicFinanciamentoRoute
  '/politica-de-privacidade': typeof PublicPoliticaDePrivacidadeRoute
  '/sobre': typeof PublicSobreRoute
  '/venda-seu-veiculo': typeof PublicVendaSeuVeiculoRoute
  '/admin/atividade': typeof AdminAtividadeRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/relatorios': typeof AdminRelatoriosRoute
  '/': typeof PublicIndexRoute
  '/admin': typeof AdminIndexRoute
  '/veiculo/$slug': typeof PublicVeiculoSlugRoute
  '/admin/financeiro/custos': typeof AdminFinanceiroCustosRoute
  '/admin/financeiro/pagar': typeof AdminFinanceiroPagarRoute
  '/admin/financeiro/receber': typeof AdminFinanceiroReceberRoute
  '/admin/marketing/conteudo': typeof AdminMarketingConteudoRoute
  '/admin/marketing/publicacoes': typeof AdminMarketingPublicacoesRoute
  '/admin/veiculos/$id': typeof AdminVeiculosIdRoute
  '/admin/veiculos/novo': typeof AdminVeiculosNovoRoute
  '/admin/veiculos/producao': typeof AdminVeiculosProducaoRoute
  '/admin/veiculos/qualidade': typeof AdminVeiculosQualidadeRoute
  '/admin/vendas/comissoes': typeof AdminVendasComissoesRoute
  '/admin/vendas/nova': typeof AdminVendasNovaRoute
  '/admin/financeiro': typeof AdminFinanceiroIndexRoute
  '/admin/veiculos': typeof AdminVeiculosIndexRoute
  '/admin/vendas': typeof AdminVendasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public': typeof PublicRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/apresentacao': typeof ApresentacaoRoute
  '/demo-azul': typeof DemoAzulRoute
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_public/contato': typeof PublicContatoRoute
  '/_public/estoque': typeof PublicEstoqueRoute
  '/_public/financiamento': typeof PublicFinanciamentoRoute
  '/_public/politica-de-privacidade': typeof PublicPoliticaDePrivacidadeRoute
  '/_public/sobre': typeof PublicSobreRoute
  '/_public/venda-seu-veiculo': typeof PublicVendaSeuVeiculoRoute
  '/admin/atividade': typeof AdminAtividadeRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/relatorios': typeof AdminRelatoriosRoute
  '/_public/': typeof PublicIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/_public/veiculo/$slug': typeof PublicVeiculoSlugRoute
  '/admin/financeiro/custos': typeof AdminFinanceiroCustosRoute
  '/admin/financeiro/pagar': typeof AdminFinanceiroPagarRoute
  '/admin/financeiro/receber': typeof AdminFinanceiroReceberRoute
  '/admin/marketing/conteudo': typeof AdminMarketingConteudoRoute
  '/admin/marketing/publicacoes': typeof AdminMarketingPublicacoesRoute
  '/admin/veiculos/$id': typeof AdminVeiculosIdRoute
  '/admin/veiculos/novo': typeof AdminVeiculosNovoRoute
  '/admin/veiculos/producao': typeof AdminVeiculosProducaoRoute
  '/admin/veiculos/qualidade': typeof AdminVeiculosQualidadeRoute
  '/admin/vendas/comissoes': typeof AdminVendasComissoesRoute
  '/admin/vendas/nova': typeof AdminVendasNovaRoute
  '/admin/financeiro/': typeof AdminFinanceiroIndexRoute
  '/admin/veiculos/': typeof AdminVeiculosIndexRoute
  '/admin/vendas/': typeof AdminVendasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/apresentacao'
    | '/demo-azul'
    | '/login'
    | '/sitemap.xml'
    | '/contato'
    | '/estoque'
    | '/financiamento'
    | '/politica-de-privacidade'
    | '/sobre'
    | '/venda-seu-veiculo'
    | '/admin/atividade'
    | '/admin/configuracoes'
    | '/admin/relatorios'
    | '/admin/'
    | '/veiculo/$slug'
    | '/admin/financeiro/custos'
    | '/admin/financeiro/pagar'
    | '/admin/financeiro/receber'
    | '/admin/marketing/conteudo'
    | '/admin/marketing/publicacoes'
    | '/admin/veiculos/$id'
    | '/admin/veiculos/novo'
    | '/admin/veiculos/producao'
    | '/admin/veiculos/qualidade'
    | '/admin/vendas/comissoes'
    | '/admin/vendas/nova'
    | '/admin/financeiro/'
    | '/admin/veiculos/'
    | '/admin/vendas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/apresentacao'
    | '/demo-azul'
    | '/login'
    | '/sitemap.xml'
    | '/contato'
    | '/estoque'
    | '/financiamento'
    | '/politica-de-privacidade'
    | '/sobre'
    | '/venda-seu-veiculo'
    | '/admin/atividade'
    | '/admin/configuracoes'
    | '/admin/relatorios'
    | '/'
    | '/admin'
    | '/veiculo/$slug'
    | '/admin/financeiro/custos'
    | '/admin/financeiro/pagar'
    | '/admin/financeiro/receber'
    | '/admin/marketing/conteudo'
    | '/admin/marketing/publicacoes'
    | '/admin/veiculos/$id'
    | '/admin/veiculos/novo'
    | '/admin/veiculos/producao'
    | '/admin/veiculos/qualidade'
    | '/admin/vendas/comissoes'
    | '/admin/vendas/nova'
    | '/admin/financeiro'
    | '/admin/veiculos'
    | '/admin/vendas'
  id:
    | '__root__'
    | '/_public'
    | '/admin'
    | '/apresentacao'
    | '/demo-azul'
    | '/login'
    | '/sitemap.xml'
    | '/_public/contato'
    | '/_public/estoque'
    | '/_public/financiamento'
    | '/_public/politica-de-privacidade'
    | '/_public/sobre'
    | '/_public/venda-seu-veiculo'
    | '/admin/atividade'
    | '/admin/configuracoes'
    | '/admin/relatorios'
    | '/_public/'
    | '/admin/'
    | '/_public/veiculo/$slug'
    | '/admin/financeiro/custos'
    | '/admin/financeiro/pagar'
    | '/admin/financeiro/receber'
    | '/admin/marketing/conteudo'
    | '/admin/marketing/publicacoes'
    | '/admin/veiculos/$id'
    | '/admin/veiculos/novo'
    | '/admin/veiculos/producao'
    | '/admin/veiculos/qualidade'
    | '/admin/vendas/comissoes'
    | '/admin/vendas/nova'
    | '/admin/financeiro/'
    | '/admin/veiculos/'
    | '/admin/vendas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PublicRoute: typeof PublicRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  ApresentacaoRoute: typeof ApresentacaoRoute
  DemoAzulRoute: typeof DemoAzulRoute
  LoginRoute: typeof LoginRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo-azul': {
      id: '/demo-azul'
      path: '/demo-azul'
      fullPath: '/demo-azul'
      preLoaderRoute: typeof DemoAzulRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apresentacao': {
      id: '/apresentacao'
      path: '/apresentacao'
      fullPath: '/apresentacao'
      preLoaderRoute: typeof ApresentacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/admin/relatorios': {
      id: '/admin/relatorios'
      path: '/relatorios'
      fullPath: '/admin/relatorios'
      preLoaderRoute: typeof AdminRelatoriosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/configuracoes': {
      id: '/admin/configuracoes'
      path: '/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AdminConfiguracoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/atividade': {
      id: '/admin/atividade'
      path: '/atividade'
      fullPath: '/admin/atividade'
      preLoaderRoute: typeof AdminAtividadeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_public/venda-seu-veiculo': {
      id: '/_public/venda-seu-veiculo'
      path: '/venda-seu-veiculo'
      fullPath: '/venda-seu-veiculo'
      preLoaderRoute: typeof PublicVendaSeuVeiculoRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/sobre': {
      id: '/_public/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof PublicSobreRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/politica-de-privacidade': {
      id: '/_public/politica-de-privacidade'
      path: '/politica-de-privacidade'
      fullPath: '/politica-de-privacidade'
      preLoaderRoute: typeof PublicPoliticaDePrivacidadeRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/financiamento': {
      id: '/_public/financiamento'
      path: '/financiamento'
      fullPath: '/financiamento'
      preLoaderRoute: typeof PublicFinanciamentoRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/estoque': {
      id: '/_public/estoque'
      path: '/estoque'
      fullPath: '/estoque'
      preLoaderRoute: typeof PublicEstoqueRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/contato': {
      id: '/_public/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof PublicContatoRouteImport
      parentRoute: typeof PublicRoute
    }
    '/admin/vendas/': {
      id: '/admin/vendas/'
      path: '/vendas'
      fullPath: '/admin/vendas/'
      preLoaderRoute: typeof AdminVendasIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/veiculos/': {
      id: '/admin/veiculos/'
      path: '/veiculos'
      fullPath: '/admin/veiculos/'
      preLoaderRoute: typeof AdminVeiculosIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/financeiro/': {
      id: '/admin/financeiro/'
      path: '/financeiro'
      fullPath: '/admin/financeiro/'
      preLoaderRoute: typeof AdminFinanceiroIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/vendas/nova': {
      id: '/admin/vendas/nova'
      path: '/vendas/nova'
      fullPath: '/admin/vendas/nova'
      preLoaderRoute: typeof AdminVendasNovaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/vendas/comissoes': {
      id: '/admin/vendas/comissoes'
      path: '/vendas/comissoes'
      fullPath: '/admin/vendas/comissoes'
      preLoaderRoute: typeof AdminVendasComissoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/veiculos/qualidade': {
      id: '/admin/veiculos/qualidade'
      path: '/veiculos/qualidade'
      fullPath: '/admin/veiculos/qualidade'
      preLoaderRoute: typeof AdminVeiculosQualidadeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/veiculos/producao': {
      id: '/admin/veiculos/producao'
      path: '/veiculos/producao'
      fullPath: '/admin/veiculos/producao'
      preLoaderRoute: typeof AdminVeiculosProducaoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/veiculos/novo': {
      id: '/admin/veiculos/novo'
      path: '/veiculos/novo'
      fullPath: '/admin/veiculos/novo'
      preLoaderRoute: typeof AdminVeiculosNovoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/veiculos/$id': {
      id: '/admin/veiculos/$id'
      path: '/veiculos/$id'
      fullPath: '/admin/veiculos/$id'
      preLoaderRoute: typeof AdminVeiculosIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/marketing/publicacoes': {
      id: '/admin/marketing/publicacoes'
      path: '/marketing/publicacoes'
      fullPath: '/admin/marketing/publicacoes'
      preLoaderRoute: typeof AdminMarketingPublicacoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/marketing/conteudo': {
      id: '/admin/marketing/conteudo'
      path: '/marketing/conteudo'
      fullPath: '/admin/marketing/conteudo'
      preLoaderRoute: typeof AdminMarketingConteudoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/financeiro/receber': {
      id: '/admin/financeiro/receber'
      path: '/financeiro/receber'
      fullPath: '/admin/financeiro/receber'
      preLoaderRoute: typeof AdminFinanceiroReceberRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/financeiro/pagar': {
      id: '/admin/financeiro/pagar'
      path: '/financeiro/pagar'
      fullPath: '/admin/financeiro/pagar'
      preLoaderRoute: typeof AdminFinanceiroPagarRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/financeiro/custos': {
      id: '/admin/financeiro/custos'
      path: '/financeiro/custos'
      fullPath: '/admin/financeiro/custos'
      preLoaderRoute: typeof AdminFinanceiroCustosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_public/veiculo/$slug': {
      id: '/_public/veiculo/$slug'
      path: '/veiculo/$slug'
      fullPath: '/veiculo/$slug'
      preLoaderRoute: typeof PublicVeiculoSlugRouteImport
      parentRoute: typeof PublicRoute
    }
  }
}

interface PublicRouteChildren {
  PublicContatoRoute: typeof PublicContatoRoute
  PublicEstoqueRoute: typeof PublicEstoqueRoute
  PublicFinanciamentoRoute: typeof PublicFinanciamentoRoute
  PublicPoliticaDePrivacidadeRoute: typeof PublicPoliticaDePrivacidadeRoute
  PublicSobreRoute: typeof PublicSobreRoute
  PublicVendaSeuVeiculoRoute: typeof PublicVendaSeuVeiculoRoute
  PublicIndexRoute: typeof PublicIndexRoute
  PublicVeiculoSlugRoute: typeof PublicVeiculoSlugRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicContatoRoute: PublicContatoRoute,
  PublicEstoqueRoute: PublicEstoqueRoute,
  PublicFinanciamentoRoute: PublicFinanciamentoRoute,
  PublicPoliticaDePrivacidadeRoute: PublicPoliticaDePrivacidadeRoute,
  PublicSobreRoute: PublicSobreRoute,
  PublicVendaSeuVeiculoRoute: PublicVendaSeuVeiculoRoute,
  PublicIndexRoute: PublicIndexRoute,
  PublicVeiculoSlugRoute: PublicVeiculoSlugRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

interface AdminRouteChildren {
  AdminAtividadeRoute: typeof AdminAtividadeRoute
  AdminConfiguracoesRoute: typeof AdminConfiguracoesRoute
  AdminRelatoriosRoute: typeof AdminRelatoriosRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminFinanceiroCustosRoute: typeof AdminFinanceiroCustosRoute
  AdminFinanceiroPagarRoute: typeof AdminFinanceiroPagarRoute
  AdminFinanceiroReceberRoute: typeof AdminFinanceiroReceberRoute
  AdminMarketingConteudoRoute: typeof AdminMarketingConteudoRoute
  AdminMarketingPublicacoesRoute: typeof AdminMarketingPublicacoesRoute
  AdminVeiculosIdRoute: typeof AdminVeiculosIdRoute
  AdminVeiculosNovoRoute: typeof AdminVeiculosNovoRoute
  AdminVeiculosProducaoRoute: typeof AdminVeiculosProducaoRoute
  AdminVeiculosQualidadeRoute: typeof AdminVeiculosQualidadeRoute
  AdminVendasComissoesRoute: typeof AdminVendasComissoesRoute
  AdminVendasNovaRoute: typeof AdminVendasNovaRoute
  AdminFinanceiroIndexRoute: typeof AdminFinanceiroIndexRoute
  AdminVeiculosIndexRoute: typeof AdminVeiculosIndexRoute
  AdminVendasIndexRoute: typeof AdminVendasIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAtividadeRoute: AdminAtividadeRoute,
  AdminConfiguracoesRoute: AdminConfiguracoesRoute,
  AdminRelatoriosRoute: AdminRelatoriosRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminFinanceiroCustosRoute: AdminFinanceiroCustosRoute,
  AdminFinanceiroPagarRoute: AdminFinanceiroPagarRoute,
  AdminFinanceiroReceberRoute: AdminFinanceiroReceberRoute,
  AdminMarketingConteudoRoute: AdminMarketingConteudoRoute,
  AdminMarketingPublicacoesRoute: AdminMarketingPublicacoesRoute,
  AdminVeiculosIdRoute: AdminVeiculosIdRoute,
  AdminVeiculosNovoRoute: AdminVeiculosNovoRoute,
  AdminVeiculosProducaoRoute: AdminVeiculosProducaoRoute,
  AdminVeiculosQualidadeRoute: AdminVeiculosQualidadeRoute,
  AdminVendasComissoesRoute: AdminVendasComissoesRoute,
  AdminVendasNovaRoute: AdminVendasNovaRoute,
  AdminFinanceiroIndexRoute: AdminFinanceiroIndexRoute,
  AdminVeiculosIndexRoute: AdminVeiculosIndexRoute,
  AdminVendasIndexRoute: AdminVendasIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PublicRoute: PublicRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  ApresentacaoRoute: ApresentacaoRoute,
  DemoAzulRoute: DemoAzulRoute,
  LoginRoute: LoginRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
